openapi: 3.0.2
info:
  version: '1.0.0' # Your API version
components:
  schemas:
    Candle:
      description: >

        One OHLCV candle for the candle charts

      type: object
      properties:
        ts:
          description: >
            UNIX UTC timestamp as seconds when this candle started
          type: number
          format: timestamp
        o:
          description: >
            Open value of the candle
          type: number
          format: us_dollar
        h:
          description: >
            High value of the candle
          type: number
          format: us_dollar
        l:
          description: >
            Low value of the candle
          type: number
          format: us_dollar
        c:
          description: >
            Close value of the candle
          type: number
          format: us_dollar
        v:
          description: >
            Trade volume in US dollar
          type: number
          format: us_dollar
        xr:
          description: >

            `xr` stands for the exchange rate.

            Appromaxime exchange rate between US dollar and quote token for this candle.

            The actual exchange rate may be true only for 1 minute candles.
            The 1 minute candles use reference price oracle for quote token/USD.
            Other candle data is upsampled from the 1 minute candles and do not internally use any exchange rate.

            Any USD stablecoin is assumed to be 1:1 to actual USD.

          type: number
        tc:
          description: >

            `ct` stands for the trade count.

            Number of individual trades executed during the candle time period.

          type: number
    CandleList:
      description: >

        Multiple candles to render.

        Note that this data is sparse. If there were no trades, the timestamp for the candle time bucket
        period does not exist in the array.

        Candles will be sorted from the first to the last.

      results:
        description: One page of pair summaries
        type: array
        items:
          $ref: '#/components/schemas/Candle'

